### PR TITLE
Make homepage icons accessible

### PR DESCRIPTION
**Pull request by cella**
Fixes https://www.pivotaltracker.com/story/show/169551515

To make the cart svg more accessible, role and aria-labelledby attributes were added. role has been set to "img" in order to be recognized as an image by older browsers and the ARIA label has been set to "Cart".

Since the social media icons are focusable interactive elements, an aria-label attribute has been added to each link to match its title attribute. In addition, the svg element itself has aria-hidden="true" so it won't be recognized by screen readers.

### CODE REVIEW

**Comment by hwinn4** [comment]
@cella How did you get the social media icons to show locally?

**Comment by cella** [comment]
@hwinn4 I had to fake it a little bit by taking out the conditional in the template

**Comment by hwinn4** [comment]
@cella Ah okie dokie

**Comment by cella** [comment]
Hmmm I just checked and it didn't seem to make a difference in both VoiceOver and ChromeVox of differentiative an svg with aria-hidden vs not, so not sure!

**Comment by cella** [comment]
Ah according to this reference "SVG files may contain a title element which may or may not get announced by screen readers (depending on SVG embedding technique, browser name and version, and screen reader name and version)...After a bit of testing, I found that simply adding aria-hidden="true" to the svg element solves the problem"

https://www.456bereastreet.com/archive/201609/hiding_inline_svg_icons_from_screen_readers/

**Comment by hwinn4** [comment]
@cella Hmm now I am wondering about the usefulness of aria-hidden. Am I understanding correctly that that resource is focusing on icons that are used inline with text? The social media icons are just icons-- no associated text is rendered. So in our case, there is not a risk of the screen reader speaking the SVG title and the associated text. 

We can continue to add aria-hidden for good measure-- I'm not opposed to it. I like exploring the "why" behind things, so I wanted to follow up on this a bit more.

**Pull request merged**
